# file encoding
FILE_ENCODING = 'utf-8'
SPLIT_LINE = '--------------------'

# -- tokenizer --
# token type
CONSTANT_TOKEN_TYPE_KEYWORD = 0
CONSTANT_TOKEN_TYPE_SEPARATOR = 1
CONSTANT_TOKEN_TYPE_OPERATOR = 2
CONSTANT_TOKEN_TYPE_IDENTIFIER = 3
CONSTANT_TOKEN_TYPE_CONSTANT = 4
CONSTANT_TOKEN_TYPE_UNKNOWN = -1

# token set
CONSTANT_SET_KEYWORDS = {'if', 'else', 'while', 'int', 'float'}
CONSTANT_SET_OPERATORS = {'>=', '-', '(', '*', '==', '>', '+', '<', '<=', '/', '‘', '!=', '=', ')'}
CONSTANT_SET_SEPARATORS = {';'}  # not operator?
CONSTANT_TOKEN_NAME_IDENTIFIER = 'id'
CONSTANT_TOKEN_NAME_CONSTANT = 'digits'
CONSTANT_TOKEN_NAME_KEYWORD_IF = "if"
CONSTANT_TOKEN_NAME_KEYWORD_ELSE = "else"

# -- grammar sheet --
CONSTANT_GENERATOR_TYPE_END = 0
CONSTANT_GENERATOR_TYPE_NONE_END = 1
CONSTANT_GENERATOR_NONE = "ε"

CONSTANT_ACTION_FORWARD_J = 0
CONSTANT_ACTION_REDUCTION_A = 1
CONSTANT_ACTION_ACCEPT = 2
CONSTANT_ACTION_NONE = -1

# SDD attrs
CONSTANT_SDD_ATTR_TYPE = "sdd_type"
CONSTANT_SDD_ATTR_WIDTH = "sdd_width"
CONSTANT_SDD_ATTR_NAME = 'sdd_name'
CONSTANT_SDD_ATTR_VALUE = 'sdd_value'
CONSTANT_SDD_ATTR_CODE = 'sdd_code'
CONSTANT_SDD_ATTR_NEXT = 'sdd_next'
